"""remove exemple column to modes

Revision ID: 01edb5bad2ca
Revises: 5420393aa6f0
Create Date: 2026-02-10 20:22:38.496565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01edb5bad2ca'
down_revision: Union[str, Sequence[str], None] = '5420393aa6f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modes', 'exemple')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modes', sa.Column('exemple', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
