"""add validite to livreurs

Revision ID: 34d74139123b
Revises: 01edb5bad2ca
Create Date: 2026-02-25 21:08:35.320321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34d74139123b'
down_revision: Union[str, Sequence[str], None] = '01edb5bad2ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livraisons')
    op.drop_table('livreurs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livreurs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nom', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('livraisons',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('frais', sa.INTEGER(), nullable=True),
    sa.Column('adresse', sa.VARCHAR(), nullable=True),
    sa.Column('id_commande', sa.INTEGER(), nullable=True),
    sa.Column('id_livreur', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_commande'], ['commandes.id'], ),
    sa.ForeignKeyConstraint(['id_livreur'], ['livreurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
