"""add exemple column to modes

Revision ID: 5420393aa6f0
Revises: 
Create Date: 2026-02-10 20:18:33.996209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5420393aa6f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livreurs')
    op.drop_table('livraisons')
    op.add_column('modes', sa.Column('exemple', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modes', 'exemple')
    op.create_table('livraisons',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('frais', sa.INTEGER(), nullable=True),
    sa.Column('adresse', sa.VARCHAR(), nullable=True),
    sa.Column('id_commande', sa.INTEGER(), nullable=True),
    sa.Column('id_livreur', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_commande'], ['commandes.id'], ),
    sa.ForeignKeyConstraint(['id_livreur'], ['livreurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livreurs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nom', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    # ### end Alembic commands ###
